### ISSUE TITLE
If possible, add warnings to command version

### ISSUE THREAD

**Issue by ShinShil** [KorbinianKuhn/raml2html-material-theme#5]
`raml2html --theme raml2html-material-theme -i test.raml -o test.html`

One time I run the code from the above and I have not seen any errors or warnings, but the html page is not rendering well. I have copied the source from your example folder: https://github.com/KorbinianKuhn/raml2html-material-theme/edit/master/example/api.raml , check with it and discovered that all should be working. So I have recreated my code on the https://www.mulesoft.com/platform/api/api-designer , copy-paste, recompile and all start working. 

I don't know what was wrong, maybe the problem was that I have used the 'tab' instead of spaces, in that case it would be usefull to see some warn "You are using tab, use spaces instead".

For now I don't edit the raml in notepad, just copy-paste from https://www.mulesoft.com/platform/api/api-designer . And usually all works well.

**Comment by KorbinianKuhn** [comment]
I'll check if the theme can handle this tabs error itself.

**Comment by KorbinianKuhn** [comment]
Should be more robust with the new theme now
