### ISSUE TITLE
Render the response's examples the similar to parameters examples

### ISSUE THREAD

**Issue by ShinShil** [KorbinianKuhn/raml2html-material-theme#7]
I have tested with examples for responses and see the next result:

![image](https://user-images.githubusercontent.com/11064696/49691485-8e6af900-fb54-11e8-8639-32957191c115.png)

I like how it done in the body's params section

![image](https://user-images.githubusercontent.com/11064696/49691499-af334e80-fb54-11e8-8136-3a60091ad88f.png)

Is it possible to make 'Examples' word bold(as header of the examples section), and wrap the response's examples into accordion, as in the body's params section?

**Comment by KorbinianKuhn** [comment]
I'm currently working on a rewrite of the theme. To change the examples as you proposed is a good idea. I'll integrate this with the rewrite.

**Comment by KorbinianKuhn** [comment]
Hi ShinShil,

after testing the v2 of the theme in my projects for some time I released v2 on npm today. Let me know if you have trouble with the new theme.
